seed_everything: 3407

trainer:
  accelerator: gpu
  devices: 1
  precision: 32-true
  strategy:
    class_path: pytorch_lightning.strategies.DeepSpeedStrategy
    init_args:
      stage: 2
      offload_optimizer: false
      cpu_checkpointing: false
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: reprover-gnn
      name: gated_gnn_standard_reg
      save_dir: lightning_logs/gated_gnn_standard_reg
  gradient_clip_val: 1.0
  accumulate_grad_batches: 6
  max_steps: 200000
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        verbose: true
        save_top_k: 1
        save_last: true
        monitor: R@10_val # Monitor validation recall
        mode: max       # Higher recall is better
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: R@10_val # Monitor the same metric
        patience: 3       # Stop if no improvement after 3 validation epochs
        mode: max         # Higher is better
        verbose: true

model:
  feature_size: 1472
  num_layers: 2
  lr: 1e-6
  warmup_steps: 0
  loss_function: mse
  l1_lambda: 0.0 # Standard L1 regularization
  weight_decay: 1e-4 # Standard L2 regularization
  edge_type_to_id: {}
  
  # --- GNN Architecture ---
  gnn_layer_type: gated-rgcn # Use the new Gated RGCN layer
  hidden_size: 1472
  use_residual: false
  dropout_p: 0.3 # Standard dropout
  edge_dropout_p: 0.1 # Standard edge dropout
  norm_type: layer # Standard normalization
  use_initial_projection: false # Required since feature_size != hidden_size
  postprocess_gnn_embeddings: gnn # Use only GNN output as requested

data:
  data_path: data/leandojo_benchmark_4/random/
  corpus_path: data/leandojo_benchmark_4/corpus.jsonl
  retriever_ckpt_path: kaiyuy/leandojo-lean4-retriever-byt5-small

  batch_size: 5120 # effective_batch_size == batch_size * accumulate_grad_batches * devices
  eval_batch_size: 4
  num_workers: 6

  negative_mining:
    strategy: hard
    num_negatives: 4
    num_in_file_negatives: 1

  graph_dependencies_config:
    mode: custom
    use_proof_dependencies: false
    signature_and_state:
      verbosity: clickable
      distinguish_lctx_goal: true

  attributes:
    use_node_attributes: true