# In retrieval/confs/cli_gnn.yaml

seed_everything: 3407
trainer:
  accelerator: gpu
  devices: 1
  precision: bf16-mixed
  strategy:
    class_path: pytorch_lightning.strategies.DeepSpeedStrategy
    init_args:
      stage: 2
      offload_optimizer: false
      cpu_checkpointing: false
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: reprover-gnn
      name: gnn_retriever1
      save_dir: "lightning_logs/gnn_retriever"
  gradient_clip_val: 1.0
  max_steps: 200000
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        verbose: true
        save_top_k: 1
        save_last: true
        monitor: loss_train_epoch
        mode: min

model:
  feature_size: 1472
  num_layers: 2
  lr: 1e-4
  warmup_steps: 1000

data:
  data_path: data/leandojo_benchmark_4/random/
  corpus_path: data/leandojo_benchmark_4/corpus.jsonl
  embeddings_path: data/leandojo_benchmark_4/embeddings/premise_embeddings.pt # IMPORTANT: Set this path
  retriever_ckpt_path: kaiyuy/leandojo-lean4-retriever-byt5-small
  num_negatives: 3
  num_in_file_negatives: 1
  batch_size: 8
  eval_batch_size: 4
  num_workers: 4
  
  # New parametrization scheme for graph construction
  graph_dependencies:
    mode: 'custom'                 # 'all_dojo' or 'custom'
    use_proof_dependencies: true
    signature_and_state:
      verbosity: 'clickable'       # 'clickable', 'verbose', or 'dojo'
      distinguish_lctx_goal: true

  attributes:
    use_node_attributes: true      # This key is not used in the GNN model yet but is good practice to include